import re
from datetime import datetime, timezone
from typing import Any

from app.models import scanner_data
from app.schemas.scanner import ScannerPayload
from app.repositories.inventory import ComputerRepository

class InventoryService:
    def __init__(self, repository: ComputerRepository):
        """Initializes the inventory service with its required repository.

        Args:
            repository (ComputerRepository): The repository for computer database operations.
        """
        self.repository = repository

    @staticmethod
    def parse_powershell_date(date_str: str | None) -> datetime | None:
        """Converts a PowerShell specific date string format into a Python datetime object.

        Args:
            date_str (str | None): The date string generated by PowerShell (e.g., '/Date(1743786151000)/').

        Returns:
            datetime | None: A UTC datetime object representing the extracted timestamp, or None if the input is invalid or missing.
        """
        if not date_str:
            return None
        match = re.search(r'\d+', date_str)
        if match:
            timestamp_ms = int(match.group())
            return datetime.fromtimestamp(timestamp_ms / 1000.0, tz=timezone.utc)
        return None

    @staticmethod
    def ensure_list(item: Any) -> list:
        """Ensures that the provided item is consistently returned as a list.

        Args:
            item (Any): A single object, a list of objects, or None received from the JSON payload.

        Returns:
            list: An empty list if the item is None, the item itself if it is already a list, or a new list containing the single item.
        """
        if item is None:
            return []
        if not isinstance(item, list):
            return [item]
        return item
    @staticmethod
    def clean_null_chars(text: Any) -> Any:
        """Removes NUL (0x00) characters from strings to prevent database ValueError."""
        if isinstance(text, str):
            return text.replace('\x00', '').strip()
        return text

    def process_inventory_payload(self, payload: ScannerPayload) -> scanner_data.Computer:
        """Processes the hardware and software payload, orchestrating the UPSERT logic.

        Args:
            payload (ScannerPayload): The validated Pydantic schema containing all the data collected by the PowerShell scanner.

        Returns:
            scanner_data.Computer: The created or updated SQLAlchemy database model representing the computer.
        """
        
        db_computer = self.repository.get_by_serial(payload.system.serial_num)

        is_new = False
        if not db_computer:
            db_computer = scanner_data.Computer(serial_num=payload.system.serial_num)
            is_new = True

        db_computer.hostname = payload.system.hostname
        db_computer.manufacturer = payload.system.manufacturer
        db_computer.model = payload.system.model
        db_computer.equipment_type = payload.system.equipment_type
        db_computer.bios_version = payload.system.bios_version
        db_computer.cpu = payload.system.cpu
        db_computer.ram_gb = payload.system.ram_gb
        db_computer.operating_system = payload.system.operating_system
        db_computer.os_installation_date = self.parse_powershell_date(payload.system.os_installation_date)
        db_computer.activity_time = payload.system.activity_time
        db_computer.last_user = payload.system.last_user
        db_computer.battery_health = payload.system.battery_health
        
        db_computer.antivirus = payload.security.antivirus
        db_computer.local_admins = payload.security.local_admins
        db_computer.reboot_pending = payload.security.reboot_pending
        db_computer.last_verification = payload.verification_date

        db_computer.disks = [
            scanner_data.Disk(drive=d.drive, size_gb=d.size_gb, free_gb=d.free_gb)
            for d in self.ensure_list(payload.disks)
        ]
        
        db_computer.monitors = [
            scanner_data.Monitor(
                manufacturer=self.clean_null_chars(m.manufacturer), 
                model=self.clean_null_chars(m.model), 
                serial_num=self.clean_null_chars(m.serial_num)
            )
            for m in self.ensure_list(payload.monitors)
        ]
        
        db_computer.networks = [
            scanner_data.Network(adapter_name=n.adapter_name, mac_address=n.mac_address, ip_address=n.ip_address)
            for n in self.ensure_list(payload.networks)
        ]
        
        db_computer.softwares = [
            scanner_data.Software(software_name=s.software_name, version=s.version)
            for s in self.ensure_list(payload.softwares)
        ]

        return self.repository.save(db_computer, is_new)